Added arg validations for es-count-types

diff --git a/bin/es-count-types b/bin/es-count-types
--- a/bin/es-count-types
+++ b/bin/es-count-types
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+if [[ $# -ne 2 ]]; then
+    echo "Missing parameters."
+    echo "`basename $0` <ELASTICSEARCH_HOST> <INDEX_NAME>"
+    exit 1
+fi
+
 ELASTICSEARCH_HOST=$1
 INDEX_NAME=$2
 
